# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x0b\x63\x61lculadora\",\n\x08Operacao\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\x12\n\n\x02op\x18\x03 \x01(\t\"(\n\tResultado\x12\r\n\x05valor\x18\x01 \x01(\x02\x12\x0c\n\x04\x65rro\x18\x02 \x01(\t2H\n\x0b\x43\x61lculadora\x12\x39\n\x08\x43\x61lcular\x12\x15.calculadora.Operacao\x1a\x16.calculadora.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACAO']._serialized_start=27
  _globals['_OPERACAO']._serialized_end=71
  _globals['_RESULTADO']._serialized_start=73
  _globals['_RESULTADO']._serialized_end=113
  _globals['_CALCULADORA']._serialized_start=115
  _globals['_CALCULADORA']._serialized_end=187
# @@protoc_insertion_point(module_scope)
